/**
 * PR-1 instrument: determine how a CLIENT-INITIATED signInWithOtp formats the
 * callback URL under this repo's @supabase/ssr PKCE configuration.
 *
 * Why this exists: `docs/decisions/2026-07-27-generation-requires-sign-in.md`
 * scopes replacing Google with magic link. The callback design depends entirely
 * on whether the link lands as `?code=` (server-readable), `?token_hash=`
 * (server-readable) or `#fragment` (NOT server-readable — needs a client
 * component reading window.location.hash). An admin-generated link was measured
 * landing as a FRAGMENT, but admin links carry no PKCE challenge, so that
 * observation does not answer the client case.
 *
 * HARNESS FIDELITY — the thing this script must prove before its result means
 * anything. The code_verifier is generated by the client calling signInWithOtp
 * and written to that client's storage. A Node client with no persistent
 * storage might not send a code_challenge at all, in which case a fragment
 * result would be an artifact of the harness rather than the app's behaviour.
 * So `--dry` mode intercepts the outgoing POST /otp and reports whether
 * `code_challenge` is actually on the wire, WITHOUT sending any email.
 *
 * Usage (from web/):
 *   npx tsx --env-file=.env.development.local scripts/test-magic-link-pkce.ts --dry
 *   npx tsx --env-file=.env.development.local scripts/test-magic-link-pkce.ts --send <email>
 *
 * TEST ONLY — asserts the project ref before doing anything.
 * Zero diff to web/src/. This script imports the app's client factory rather
 * than reconstructing one, so PKCE is configured identically by construction.
 */
import { createBrowserClient } from "@supabase/ssr";

const TEST_REF = "znldzjdatkogdktymtvi";
const REDIRECT = "http://localhost:3210/auth/callback?next=/trips";

type Captured = { url: string; body: Record<string, unknown> | null };

function parseArgs() {
  const a = process.argv.slice(2);
  const send = a.includes("--send");
  const email = send ? a[a.indexOf("--send") + 1] : undefined;
  return { send, email, dry: a.includes("--dry") || !send };
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  const anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";
  const ref = url.match(/https:\/\/([a-z0-9]+)\.supabase/)?.[1] ?? "?";
  if (ref !== TEST_REF) throw new Error(`TEST-ref-or-abort: got ${ref}`);
  if (!anon) throw new Error("NEXT_PUBLIC_SUPABASE_ANON_KEY missing");
  if (anon.startsWith("sb_secret_"))
    throw new Error("anon key is a SECRET key — refusing; this must run as the browser role");

  const { send, email, dry } = parseArgs();
  if (send && !email) throw new Error("--send requires an email address");

  const captured: Captured[] = [];
  const realFetch = globalThis.fetch;
  const spyFetch: typeof fetch = async (input, init) => {
    const u = typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
    let body: Record<string, unknown> | null = null;
    try {
      body = init?.body ? JSON.parse(String(init.body)) : null;
    } catch {
      body = null;
    }
    captured.push({ url: u, body });
    if (dry && u.includes("/auth/v1/otp")) {
      // Do not transmit. Return a synthetic refusal so the SDK unwinds cleanly.
      return new Response(JSON.stringify({ code: 400, msg: "DRY RUN — not sent" }), {
        status: 400,
        headers: { "content-type": "application/json" },
      });
    }
    return realFetch(input as RequestInfo, init);
  };

  // Same factory as web/src/lib/supabase/client.ts (`createBrowserClient`), so
  // flowType is pinned to "pkce" by the library itself and cannot be overridden.
  //
  // The app calls it with NO options. That form does not initialise in Node —
  // @supabase/ssr warns that getAll/setAll "were needed" and the storage adapter
  // then never resolves, so the call hangs. We therefore supply an in-memory
  // cookie jar.
  //
  // Why that is still faithful for the question being asked: per
  // node_modules/@supabase/auth-js GoTrueClient.signInWithOtp, the challenge is
  // computed whenever `this.flowType === 'pkce'` — storage only determines WHERE
  // the verifier is written, never WHETHER a challenge is sent. The `--dry`
  // output below proves that on the wire rather than assuming it. The one thing
  // the memory jar cannot do is survive the process, so this harness can never
  // COMPLETE an exchange — it only establishes the redirect SHAPE.
  const jar = new Map<string, string>();
  const supabase = createBrowserClient(url, anon, {
    global: { fetch: spyFetch },
    isSingleton: false,
    cookies: {
      getAll: () => [...jar.entries()].map(([name, value]) => ({ name, value })),
      setAll: (items) => items.forEach(({ name, value }) => jar.set(name, value)),
    },
  });

  const target = send ? email! : "harness-fidelity-probe@example.com";
  console.log(`mode        : ${send ? "SEND (real email)" : "DRY (nothing transmitted)"}`);
  console.log(`project     : TEST (${ref})`);
  console.log(`recipient   : ${target}`);
  console.log(`redirect_to : ${REDIRECT}\n`);

  const { error } = await supabase.auth.signInWithOtp({
    email: target,
    options: { emailRedirectTo: REDIRECT, shouldCreateUser: true },
  });

  const otp = captured.find((c) => c.url.includes("/auth/v1/otp"));
  const cc = otp?.body?.code_challenge;
  const ccm = otp?.body?.code_challenge_method;

  console.log("=== HARNESS FIDELITY ===");
  console.log(`  POST /otp intercepted     : ${otp ? "yes" : "NO — nothing sent"}`);
  console.log(`  code_challenge on the wire: ${cc ? "YES" : "NO"}`);
  console.log(`  code_challenge_method     : ${ccm ?? "(absent)"}`);
  console.log(`  body keys                 : ${otp?.body ? Object.keys(otp.body).join(", ") : "—"}`);

  // Where did the verifier land? Read it back through the SDK's own storage.
  const verifierKeys = [...jar.keys()].filter((k) => k.includes("code-verifier"));
  console.log(
    `  code_verifier stored at   : ${
      verifierKeys.length ? verifierKeys.join(", ") + "  (in-memory jar — lost on exit)" : "(none found)"
    }`,
  );
  console.log(
    `\n  VERDICT: ${
      cc
        ? "FAITHFUL for the shape question — GoTrue receives a PKCE challenge, so the\n           redirect shape it chooses is the same one a browser would get."
        : "NOT FAITHFUL — no code_challenge was sent. A fragment result here would be\n           a harness artifact. Answer must come from a real browser instead."
    }`,
  );

  if (dry) {
    console.log("\n  DRY RUN — no email transmitted, no rate limit spent.");
    return;
  }
  if (error) {
    console.log(`\n  signInWithOtp error: ${error.message}`);
    process.exit(1);
  }
  console.log("\n  signInWithOtp returned OK — Supabase accepted the request; email dispatched.");
  console.log("  Retrieve the link from the inbox. Do NOT click it.");
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
