/**
 * Deploy the LA→Deadhorse corridor as three rows in ingestion_corridor:
 * Segment A (LA→PNW), Segment B (Canada west), Segment C (YT/AK).
 *
 * Source of truth for the route polyline: web/src/lib/trips/alaska-route.ts
 * (pre-baked road-following polyline5, generated by web/scripts/prebake-routes.mjs).
 * We read it via fs to keep the data/ workspace independent of web/ at
 * import time — there's no shared TS package yet, and tsconfig boundaries
 * keep them apart. Re-extract the const value by regex; the file format
 * is stable (machine-generated header + single string export).
 *
 * Segment boundaries (per phase-3-corridor-expansion-spec.md §2.1 +
 * Adam's confirmation):
 *   - A: LA (~34°N) → last route point south of the WA/BC border (~49°N)
 *   - B: BC/AB (~49°N) → last point south of the YT border (~60°N)
 *   - C: YT/AK (~60°N) → Deadhorse (~70°N)
 *
 * Buffer: 80km (~50mi), matching the existing ingestion_corridor default.
 * Downsample: ~2000 vertices per full route (~600/segment) — generous
 * for a buffer that's 80km wide.
 *
 * Idempotent: upserts on `ingestion_corridor.name`. Re-running with the
 * same source polyline produces identical rows.
 *
 * Run:
 *   npm run -w data deploy-corridor
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { getDb } from "../ingestion/lib/db.ts";
import { logger } from "../ingestion/lib/logger.ts";
import { decodePolyline, downsample } from "../ingestion/lib/polyline.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROUTE_FILE = resolve(HERE, "../../web/src/lib/trips/alaska-route.ts");

const BUFFER_METERS = 80000;
const TARGET_VERTICES_TOTAL = 2000;

interface SegmentDef {
  name: string;
  /** Inclusive lower lat bound. */
  latMin: number;
  /** Exclusive upper lat bound. The point that crosses this becomes the LAST point of the segment. */
  latMax: number;
}

// Segment latitude windows. The route runs broadly south→north; we
// slice on the first crossing of each threshold in route order.
const SEGMENTS: readonly SegmentDef[] = [
  { name: "segment_a_la_pnw", latMin: -90, latMax: 49.0 },
  { name: "segment_b_bc_ab", latMin: 49.0, latMax: 60.0 },
  { name: "segment_c_yt_ak", latMin: 60.0, latMax: 90 },
] as const;

function loadPolyline(): string {
  const text = readFileSync(ROUTE_FILE, "utf8");
  // The export is: export const LA_TO_DEADHORSE_POLYLINE: string = "..."
  // The encoded polyline never contains an unescaped double quote (the
  // polyline5 alphabet is ASCII 63–126, char " = 34 is outside it).
  const match = text.match(/LA_TO_DEADHORSE_POLYLINE[^"]*"([^"]+)"/);
  if (!match || match[1] === undefined) {
    throw new Error(`Could not extract LA_TO_DEADHORSE_POLYLINE from ${ROUTE_FILE}`);
  }
  return match[1];
}

/**
 * Split coords into the SEGMENTS by latitude bands, in route order.
 * Each coord goes into the first segment whose [latMin, latMax) range
 * it satisfies. Walking in route order yields a single contiguous slice
 * per segment for the LA→Deadhorse direction.
 */
function sliceIntoSegments(coords: [number, number][]): Record<string, [number, number][]> {
  const out: Record<string, [number, number][]> = {};
  for (const seg of SEGMENTS) out[seg.name] = [];

  for (const coord of coords) {
    const lat = coord[1];
    for (const seg of SEGMENTS) {
      if (lat >= seg.latMin && lat < seg.latMax) {
        out[seg.name]!.push(coord);
        break;
      }
    }
  }
  return out;
}

/** Build a PostGIS WKT LineString from [lng, lat] pairs (4326 SRID). */
function toLineStringWkt(coords: [number, number][]): string {
  if (coords.length < 2) {
    throw new Error(`LineString requires at least 2 vertices, got ${coords.length}`);
  }
  const points = coords.map(([lng, lat]) => `${lng} ${lat}`).join(",");
  return `SRID=4326;LINESTRING(${points})`;
}

async function upsertSegment(
  name: string,
  coords: [number, number][],
): Promise<{ id: string; vertices: number; bbox: [number, number, number, number] }> {
  const wkt = toLineStringWkt(coords);

  // Compute the raw bbox of the centerline for the log line. The
  // active_corridor_buffer view will recompute a buffered envelope
  // server-side; this is just for human-visible reporting.
  const lngs = coords.map((c) => c[0]);
  const lats = coords.map((c) => c[1]);
  const bbox: [number, number, number, number] = [
    Math.min(...lngs),
    Math.min(...lats),
    Math.max(...lngs),
    Math.max(...lats),
  ];

  const db = getDb();
  const { data, error } = await db
    .from("ingestion_corridor")
    .upsert(
      {
        name,
        geometry: wkt,
        buffer_meters: BUFFER_METERS,
        active: true,
        status: "pending",
      },
      { onConflict: "name" },
    )
    .select("id")
    .single();

  if (error) throw error;
  return { id: (data as { id: string }).id, vertices: coords.length, bbox };
}

async function main(): Promise<void> {
  logger.info({ source: ROUTE_FILE }, "deploy-corridor: loading polyline");
  const encoded = loadPolyline();
  const allCoords = decodePolyline(encoded);
  logger.info({ rawVertices: allCoords.length }, "deploy-corridor: polyline decoded");

  // Downsample the whole route once, then slice — keeps the segment
  // sizing proportional to the source density.
  const reduced = downsample(allCoords, TARGET_VERTICES_TOTAL);
  logger.info({ reducedVertices: reduced.length }, "deploy-corridor: downsampled");

  const sliced = sliceIntoSegments(reduced);

  for (const seg of SEGMENTS) {
    const coords = sliced[seg.name] ?? [];
    if (coords.length < 2) {
      logger.warn(
        { segment: seg.name, vertices: coords.length },
        "deploy-corridor: segment has <2 vertices — skipping",
      );
      continue;
    }
    const result = await upsertSegment(seg.name, coords);
    logger.info(
      {
        segment: seg.name,
        id: result.id,
        vertices: result.vertices,
        bbox: result.bbox,
        bufferKm: BUFFER_METERS / 1000,
      },
      "deploy-corridor: upserted",
    );
  }

  logger.info("deploy-corridor: complete");
}

main().catch((err) => {
  logger.error({ err }, "deploy-corridor: fatal");
  process.exit(1);
});
